version: '3'
services:
  web:
    build: ./web
    working_dir: '/home/cham11ng/lets-express'
    volumes:
      - /home/cham11ng/WebstormProjects/lets-express:/home/cham11ng/lets-express
    ports:
      - "8888:8888"
    command: bash -c "cd /home/cham11ng/lets-express && yarn install && yarn start:dev"
